version: '3.8'
services:
  server:
    image: "node:16.15.0-alpine"
    container_name: server
    entrypoint:
      - "sh"
      - "-c"
      - "yarn install && yarn start"
    working_dir: "/app"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
     - ./dump:/dump
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/

volumes:
  mongodb:
  mongodb_config: