version: "3.8"
services:
  server:
    build: .
    container_name: server
    working_dir: "/app"
    environment:
      port: 3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: authusers
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - ./dump:/dump
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongodb_config:
